[tool.poetry]
name = "jupyter_mindmaps"
version = "2.0.0"
description = "Mindmaps of Space (massive refactor version)"
authors = ["John Capobianco <ptcapo@gmail.com>"]
packages = [{ include = "jupyter_mindmaps", from = "src"}]
readme = "README.md"
include = ["src/templates/*.j2"]

[tool.poetry.scripts]
jupyter_mindmaps = 'jupyter_mindmaps.cli:run'

[tool.poetry.dependencies]
python = "^3.10"
Jinja2 = "^3.1.2"
rich-click = "^1.5.2"
httpx = "^0.23.0"
blessed = "^1.19.1"

[tool.poetry.dev-dependencies]
pylint = "^2.14.5"
mypy = "^0.971"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
